### ISSUE TITLE
java.sql.SQLRecoverableException: IO Error: Unknown host specified  when trying to start a springboot project

### ISSUE THREAD

**Issue by ValentinIacov** [oracle/oracle-db-examples#151]
Hello,

I am trying to write a very basic spring boot app that connects to an Oracle Database(The database is located on a different machine, to be able to access it I am using a VPN to have access) but I keep getting an exception.
I am able to connect from my local machine to may remote oracle database via sqlDeveloper being on VPN.
If I am not connected to VPN I got the same error in sqlDeveloper.

This is the error when running mvn spring-boot:run command from my Intelij IDE terminal:

2021-05-11 02:23:16.904  INFO 7878 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-05-11 02:23:18.396 ERROR 7878 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

java.sql.SQLRecoverableException: IO Error: Unknown host specified 
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:489) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
        at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:553) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
        at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:254) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:528) ~[ojdbc6-11.2.0.4.jar:11.2.0.4.0]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136) ~[HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) [HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) [HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) [HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) [HikariCP-3.2.0.jar:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) [spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) [spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) [spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:319) [spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:356) [spring-jdbc-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.boot.autoconfigure.jooq.SqlDialectLookup.getDialect(SqlDialectLookup.java:52) [spring-boot-autoconfigure-2.1.4.RELEASE.jar:2.1.4.RELEASE]

I am using the following dependency for the oracle jdbc driver in my pom.xml file:

        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>12.2.0.1</version>
            <scope>runtime</scope>
        </dependency>

My application.yaml file looks like this:

spring:
  datasource:
    url: jdbc:oracle:thin:@//HOSTNAME:1521/SERVICENAME
    username: USERNAME
    password: PASSWORD
    driver-class-name: oracle.jdbc.OracleDriver

Please tell me if any of the configuration is wrong or suggest what to change in order to be able to access my remote oracle database via a spring boot app.

**Comment by jeandelavarene** [comment]
First of all I recommend upgrading to the latest driver. 12.2.0.1 is very old. You can find the latest 19c driver on Maven: https://search.maven.org/artifact/com.oracle.database.jdbc/ojdbc8-production/19.10.0.0/pom
You may also have to connect through an HTTP proxy. Please refer to this doc:
https://docs.oracle.com/en/cloud/paas/autonomous-database/adbsa/connect-jdbc-thin-wallet.html#GUID-D583E056-CB47-4860-B303-039DEDEC49B8

**Comment by ValentinIacov** [comment]
Hello @jeandelavarene,

Thank you for the response, I was able to solve the issue by replacing the host name with the ip address of it.
The sqlDeveloper was running on my Windows machine but my spring boot app was running on a linux virtual machine and the linux machine was not able to resolve the host name.
